name: Scala CI

on:
  push:
    branches: [ WA-04-CSS ]
  pull_request:
    branches: [ WA-04-CSS ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: compile
        run: sbt compile